---
# vars file for /etc/ansible/roles/nginx
ip_address: 172.16.10.100
o_port: 443
port: 8095
key_path: /etc/ssl/private
certs_path: /etc/ssl/certs
ssl_certificate_path: /etc/ssl/certs/nginx-selfsigned.crt
ssl_certificate_key_path: /etc/ssl/private/nginx-selfsigned.key
ssl_dhparam_path: /etc/ssl/certs/dhparam.pem
