---

# Ansible role to install Oracle Java 8

  - name: Check If java is already installed or not
    shell: "{{ java_name }}/bin/java -version 2>&1 | grep version | awk '{print $3}' | sed 's/\"//g'"
    register: java_installed

  - name: Installed java version
    debug: "msg={{java_installed.stdout}}"

  - block:
    - name: Download Java
      command: yum install -y java-1.8.0-openjdk.x86_64

    when: java_installed.stdout == ""
